sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # Decrypt the IAM google key and add it to the project directory
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # Get and install google sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Install kubectl
  - gcloud components update kubectl
  # Authenticate with the decrypted file from IAM key
  - gcloud auth activate-service-account --key-file service-account.json
  #  Set project
  - gcloud config set project igneous-bond-280213
  #  Set compute zone
  - gcloud config set compute/zone us-central1-c
  #  Tell gcloud what cluster to work with when kuebctl is issued
  - gcloud container clusters get-credentials multi-cluster
  # Login into docker hub and specify that password is coming from stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t soguazu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run soguazu/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
