sudo: required
services:
- docker
env:
  global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: DxTHiS9p8DssldxEbC/lDNUB4jpHBPVTeftfaArCOnBxNEINO+T+a0uFE8Y2UjTFFe2n+QvgDhcUkx/owDl8K2g1OybbmCc7Lw8Dw0/1Li+chUVr1xE6S+hNWxsssV4CkGCQx/qVvXBDQ4qAAgYObGUq04Iu2gDYBNKPK403eDx6YjEx71TN6T2Vz3Z1HZuyY/FI9FU1WqTGxhuwajxQOynbtDDcxyEKwDLOFiZkzewMDxVdpV06FWQWjbxfZUWdYiE+89IR66hYi6zMutmSIkknhPqfsGxUkPDgMDdPjp4zCSB7U1rHZ5ab07DJ2vI+mQ/JT3H6lf8RkBioxUytN8Kn1a2i8OaiW9E0FfdkNHeoVBLpJwiFA7ychLeQWunedzTmz40JyGLh8a25XHLu1xmXmN/BBHmqfIIJ1GWJHGPOmBF/5GXCTS1cCi04EBdJn6rA7OPkIyiEKudnNpGoZMVbVIVGHhQlh9NrJac2yix9WBajZTX65LFOi6KcJtRO4A607aAfmGLLP3ydenKx7RwrqCDDO9NtH/g6yK/4GfcozHKcEw4ZCqHBP7+RA4j/+9t1uw6igcazSXgnNte+1jTyth1L9FFKy/NGzX96bXvOel5HpsMS1PYHg87e8DT2W/tagATlotNWscViiPy6a1JCQ/TqVzfZ6u1721yD4/0=
before_install:
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
- gcloud config set project igneous-bond-280213
- gcloud config set compute/zone us-central1-c
- gcloud container clusters get-credentials multi-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t soguazu/react-test -f ./client/Dockerfile.dev ./client
script:
- docker run soguazu/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
