apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: stanoguazu-com-tls
spec:
  secretName: stanoguazu-com
  dnsNames:
    - stanoguazu.com
    - www.stanoguazu.com
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: stanoguazu.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - stanoguazu.com
          - www.stanoguazu.com
# apiVersion: certmanager.k8s.io/v1alpha1
# kind: Certificate
# metadata:
#   name: stanoguazu-com-tls
# spec:
#   secretName: stanoguazu-com
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: stanoguazu.com
#   dnsNames:
#     - stanoguazu.com
#     - www.stanoguazu.com
#   acme:
#     config:
#       - http01:
#           ingressClass: nginx
#         domains:
#           - stanoguazu.com
#           - www.stanoguazu.com
