apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: stanoguazu-com-tls
spec:
  secretName: stanoguazu-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: stanoguazu.com
  dnsNames:
    - stanoguazu.com
    - www.stanoguazu.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - stanoguazu.com
          - www.stanoguazu.com
